Repository POWERLANE-TEAM/emplo-hrms, pull requests merged in 2024-12, with the labels that each got.

#150 chore(basic): leave request
  app/Livewire/Admin/ManageBiometricDevice.php
  app/Livewire/Calendar/Holidays.php
  app/Livewire/Employee/Leaves/RequestLeave.php
  app/Models/AttendanceLog.php
  app/Models/EmployeeLeave.php
  app/Models/Holiday.php
  app/Models/Process.php
  database/factories/AttendanceLogFactory.php
  database/migrations/2024_09_03_134109_create_holidays_table.php
  database/seeders/AttendanceLogSeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/LeaveCategorySeeder.php
  database/seeders/RolesAndPermissionsSeeder.php
  resources/js/employee/basic/leaves.js
  resources/views/employee/basic/leaves/request.blade.php
  resources/views/livewire/calendar/holidays.blade.php
  resources/views/livewire/employee/leaves/request-leave.blade.php
Labels: reference

#188 chore(models/migrations): employee `skills` `educations` `experiences`
  app/Models/Employee.php
  app/Models/EmployeeEducation.php
  app/Models/EmployeeExperience.php
  app/Models/EmployeeSkill.php
  database/migrations/2024_09_03_113157_create_employees_table.php
  database/migrations/2024_12_21_112946_create_employee_skills_table.php
  database/migrations/2024_12_21_112954_create_employee_education_table.php
  database/migrations/2024_12_21_113001_create_employee_experiences_table.php
Labels: models-migrations

#194 Confirmation Modals
  resources/images/illus/statuses/caution.png
  resources/images/illus/statuses/trashbin.png
  resources/views/components/html/test-pop-ups.blade.php
  resources/views/components/modals/confirmation/confirm-modal.blade.php
Labels: docs

#204 Separation: Resignation and Issuance of COE
  app/Enums/UserPermission.php
  app/Livewire/Employee/Separation/Resignation.php
  app/Livewire/HrManager/Separation/Coe/IssueCoeRequests.php
  app/Livewire/HrManager/Separation/Resignation/ReviewResignation.php
  database/seeders/RolesAndPermissionsSeeder.php
  resources/css/employee/hr-manager/separation.css
  resources/css/employee/hr-manager/separation.css.map
  resources/css/employee/separation.css
  resources/css/employee/separation.css.map
  resources/css/forgot-password.css
  resources/css/forgot-password.css.map
  resources/css/style.css
  resources/css/style.css.map
  resources/images/icons/sidebar/green-separation.webp
  resources/images/icons/sidebar/white-separation.webp
  resources/images/illus/empty-states/files-and-folder.webp
  resources/images/illus/statuses/check.png
  resources/js/employee/basic/separation.js
  resources/js/employee/hr-manager/separation.js
  resources/js/script.js
  resources/scss/_core.scss
  resources/scss/employee/separation.scss
  resources/scss/style.scss
  resources/views/components/gmail-redirect.blade.php
  resources/views/components/includes/callouts/data-retention-notice.blade.php
  resources/views/components/layout/employee/nav/sidebar/employee-navs.blade.php
  resources/views/components/modals/confirmation/confirm-modal.blade.php
  resources/views/employee/basic/separation/file-resignation.blade.php
  resources/views/employee/basic/separation/index.blade.php
  resources/views/employee/hr-manager/separation/coe/all.blade.php
  resources/views/employee/hr-manager/separation/coe/request.blade.php
  resources/views/employee/hr-manager/separation/resignation/all.blade.php
  resources/views/employee/hr-manager/separation/resignation/review.blade.php
  resources/views/livewire/employee/separation/resignation.blade.php
  resources/views/livewire/hr-manager/separation/coe/issue-coe-requests.blade.php
  resources/views/livewire/hr-manager/separation/resignation/review-resignation.blade.php
  routes/employee.php
Labels: docs
