Repository POWERLANE-TEAM/emplo-hrms, pull requests merged in 2024-11, with the labels that each got.

#71 Chore/hr/applications
  app/Console/Commands/Datatable/MakeCommand.php
  app/Console/Commands/Datatable/table.stub
  app/Livewire/Employee/Tables/HRManager/ApplicantsTable.php
  app/Policies/CspPolicy.php
  database/seeders/ApplicantSeeder.php
  database/seeders/DatabaseSeeder.php
  resources/css/applicant/apply.css
  resources/css/applicant/apply.css.map
  resources/css/employee/basic/dashboard.css
  resources/css/employee/basic/dashboard.css.map
  resources/css/employee/hr-manager/applicants.css
  resources/css/employee/hr-manager/applicants.css.map
  resources/css/employee/hr-manager/dashboard.css
  resources/css/employee/hr-manager/dashboard.css.map
  resources/css/employee/main.css
  resources/css/employee/main.css.map
  resources/css/employee/supervisor/dashboard.css
  resources/css/employee/supervisor/dashboard.css.map
  resources/css/hiring.css
  resources/css/hiring.css.map
  resources/css/index.css
  resources/css/index.css.map
  resources/css/login.css
  resources/css/login.css.map
  resources/css/style.css
  resources/css/style.css.map
  resources/js/employee/employee.js
  resources/js/employee/hr-manager/applicants.js
  resources/scss/_core.scss
  resources/scss/_table.scss
  resources/scss/employee/hr-manager/applicants.scss
  resources/scss/font/_font-size.scss
  resources/scss/input/_search.scss
  resources/scss/style.scss
  resources/views/components/form/select.blade.php
  resources/views/components/layout/employee/layout.blade.php
  resources/views/components/layout/employee/nav/sidebar/employee-navs.blade.php
  resources/views/components/table/filter/select-filter.blade.php
  resources/views/employee/hr-manager/applicants/index.blade.php
  resources/views/vendor/livewire-tables/components/tools/toolbar.blade.php
  resources/views/vendor/livewire-tables/components/tools/toolbar/items/search-field.blade.php
  vite.config.js
Labels: revisit

#105 build(vite): asset bundling/build process
  app/Livewire/Admin/Config/Form/PreEmployment.php
  app/Livewire/Admin/Dashboard/CalendarEvents.php
  app/Livewire/Admin/Dashboard/LaravelPulse.php
  app/Livewire/Admin/Dashboard/RecentActivityLogs.php
  app/Providers/AppServiceProvider.php
  package.json
  resources/js/admin/dashboard.js
  resources/js/app.js
  resources/js/bootstrap.js
  resources/js/listeners/online-users.js
  resources/views/apply.blade.php
  resources/views/components/layout/employee/layout.blade.php
  resources/views/components/modals/dialog.blade.php
  resources/views/components/section-wrapper.blade.php
  resources/views/employee/admin/accounts/create.blade.php
  resources/views/employee/admin/accounts/index.blade.php
  resources/views/employee/admin/announcements/announcements.blade.php
  resources/views/employee/admin/announcements/create-announcement.blade.php
  resources/views/employee/admin/config/form/pre-employment.blade.php
  resources/views/employee/admin/config/performance/categories.blade.php
  resources/views/employee/admin/index.blade.php
  resources/views/livewire/admin/accounts/create-account-form.blade.php
  resources/views/livewire/admin/config/performance/categories.blade.php
  resources/views/livewire/admin/config/performance/rating-scales.blade.php
  resources/views/livewire/admin/dashboard/calendar-events.blade.php
  resources/views/livewire/admin/dashboard/laravel-pulse.blade.php
  resources/views/livewire/admin/dashboard/online-users.blade.php
  resources/views/livewire/admin/dashboard/pulse-and-activity-logs.blade.php
  resources/views/livewire/admin/dashboard/recent-activity-logs.blade.php
  resources/views/livewire/auth/applicant/login-view.blade.php
  resources/views/livewire/auth/two-factor-challenge-form-view.blade.php
  vite.config.js
Labels: build

#109 feat: activity log
  app/Enums/ActivityLogName.php
  app/Livewire/Admin/Accounts/CreateAccountForm.php
  app/Livewire/Admin/Config/Form/PreEmployment.php
  app/Livewire/Admin/Config/Performance/Categories.php
  app/Livewire/Admin/Dashboard/LatestAnnouncements.php
  app/Livewire/Auth/Logout.php
  app/Livewire/Blocks/DragDrop/ShowDraggableData.php
  app/Livewire/Blocks/DragDrop/ShowMultDragData.php
  app/Livewire/Forms/CreateAccountForm.php
  app/Models/Announcement.php
  app/Models/Employee.php
  app/Models/JobFamily.php
  app/Models/JobTitle.php
  app/Models/JobVacancy.php
  app/Models/PerformanceCategory.php
  app/Models/PerformanceRating.php
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  app/Providers/FortifyServiceProvider.php
  config/activitylog.php
  database/migrations/2024_11_21_085534_create_activity_log_table.php
  database/migrations/2024_11_21_085535_add_event_column_to_activity_log_table.php
  database/migrations/2024_11_21_085536_add_batch_uuid_column_to_activity_log_table.php
  database/seeders/DatabaseSeeder.php
  package.json
  resources/views/livewire/admin/accounts/create-account-form.blade.php
  resources/views/livewire/blocks/dragdrop/show-draggable-data.blade.php
  resources/views/livewire/blocks/dragdrop/show-mult-drag-data.blade.php
Labels: documentation, feature
