Repository POWERLANE-TEAM/emplo-hrms, pull requests merged in 2025-02, with the labels that each got.

#272 Fix/separation
  app/Enums/FilePath.php
  app/Http/Controllers/Separation/CoeController.php
  app/Http/Controllers/Separation/ResignationController.php
  app/Livewire/CoeRequestsTable.php
  app/Livewire/Employee/Separation/Resignation.php
  app/Livewire/HrManager/Separation/Coe/IssueCoeRequests.php
  app/Livewire/ResignationTable.php
  app/Providers/FortifyServiceProvider.php
  app/Traits/NeedsWordDocToPdf.php
  composer.json
  composer.lock
  database/seeders/EmployeeSeeder.php
  resources/views/coe.blade.php
  resources/views/livewire/employee/separation/resignation.blade.php
  resources/views/livewire/hr-manager/separation/coe/issue-coe-requests.blade.php
  resources/views/pdf.blade.php
  routes/web.php
Labels: docs

#280 chore: database backup
  app/Console/Commands/SyncAttendanceLogsFromBiometricDevice.php
  app/Http/Helpers/BiometricDevice.php
  app/Livewire/Admin/Config/Performance/PeriodSetUp/Timeframe.php
  app/Livewire/Admin/Dashboard/DailyTimeRecord.php
  app/Livewire/Employee/Attendance/SyncDtrLogs.php
  app/Livewire/Employee/Overtimes/Basic/CutOffPayoutPeriods.php
  app/Livewire/Employee/Tables/IndividualEmployeeOvertimesTable.php
  app/Livewire/Tables/EmployeesAttendanceTable.php
  app/Models/AttendanceLog.php
  app/Models/EmployeeLeave.php
  app/Providers/AppServiceProvider.php
  app/Services/AttendanceService.php
  app/Traits/AttendanceUtils.php
  composer.json
  composer.lock
  config/activitylog.php
  config/backup.php
  database/migrations/2024_11_30_130241_create_attendance_logs_table.php
  database/seeders/AttendanceLogSeeder.php
  resources/views/livewire/admin/dashboard/daily-time-record.blade.php
  resources/views/livewire/employee/attendance/sync-dtr-logs.blade.php
  routes/console.php
Labels: build

#282 fix: allow overtime within payroll period only
  app/Console/Commands/OpenRegularEvaluationPeriod.php
  app/Livewire/Employee/Overtimes/Basic/RequestOvertime.php
  database/seeders/OvertimeSeeder.php
  resources/views/livewire/employee/overtimes/basic/request-overtime.blade.php
  routes/console.php
Labels: patch

#283 fix: evaluation period routing issue
  app/Enums/PerformanceEvaluationPeriod.php
  app/Enums/StatusBadge.php
  app/Livewire/Employee/Tables/AnyProbationariesPerformancesTable.php
  app/Livewire/Employee/Tables/AnyRegularsPerformancesTable.php
  app/Livewire/Employee/Tables/ProbationarySubordinatesPerformancesTable.php
  app/Livewire/Employee/Tables/RegularSubordinatesPerformancesTable.php
  app/Models/Employee.php
  app/Models/ProbationaryPerformance.php
  app/Models/ProbationaryPerformancePeriod.php
  app/Models/RegularPerformance.php
  app/Models/RegularPerformancePeriod.php
  app/Policies/RegularPerformancePolicy.php
  database/seeders/FifthMonthEvaluationSeeder.php
  database/seeders/FinalMonthEvaluationSeeder.php
  database/seeders/ThirdMonthEvaluationSeeder.php
  resources/views/components/table/employee.blade.php
  resources/views/employee/hr-manager/evaluations/probationary/all.blade.php
  resources/views/employee/hr-manager/evaluations/regular/all.blade.php
  resources/views/employee/supervisor/performance-evaluations/probationaries/all.blade.php
  resources/views/employee/supervisor/performance-evaluations/regulars/all.blade.php
Labels: patch

#285 chore(recruitment): cron job to remove rejected applications/applicants
  app/Console/Commands/DeleteRejectedApplicantsData.php
  app/Models/Application.php
  database/factories/ApplicationFactory.php
  database/migrations/2025_02_24_093227_add_rejected_at_column_to_applications_table.php
  routes/console.php
Labels: models-migrations

#286 chore: service incentive leave
  app/Console/Commands/CheckPayrollPeriodOpening.php
  app/Console/Commands/CheckProbationaryEvaluationPeriodOpening.php
  app/Console/Commands/DeleteRejectedApplicantsData.php
  app/Console/Commands/DeleteSeparatedEmployeeData.php
  app/Console/Commands/GeneratePayrollSummary.php
  app/Console/Commands/IncreaseServiceIncentiveLeaveCredits.php
  app/Console/Commands/OpenRegularEvaluationPeriod.php
  app/Console/Commands/ResetServiceIncentiveLeaveCredits.php
  app/Console/Commands/SyncAttendanceLogsFromBiometricDevice.php
  app/Enums/ServiceIncentiveLeave.php
  app/Http/Controllers/PerformanceController.php
  app/Livewire/Admin/AttendanceLogsTable.php
  app/Livewire/Admin/Dashboard/CalendarEvents.php
  app/Livewire/Employee/Attendance/GeneralAttendance.php
  app/Livewire/HrManager/Employees/Attendance.php
  app/Models/EmployeeLifecycle.php
  app/Models/EmployeeShift.php
  app/Models/ServiceIncentiveLeaveCredit.php
  app/Providers/AppServiceProvider.php
  app/Services/PayrollSummaryService.php
  app/Services/ServiceIncentiveLeaveCreditService.php
  database/migrations/2025_01_14_155212_create_service_incentive_leave_credits_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/ExperiencedEmployeeSeeder.php
  database/seeders/ServiceIncentiveLeaveCreditSeeder.php
  resources/views/livewire/admin/dashboard/calendar-events.blade.php
  routes/admin.php
  routes/console.php
Labels: models-migrations
